---
# Site

title: Galaxians Recipes
tagline: home of some out of this world recipes
url: "https://shiltemann.github.io"
baseurl: /recipes

# SEO
logo: /siteicon.png

description: The best place in the universe to find some lovely recipes written by the galactic girlfriends.

social:
  name: Galaxians Recipes
  links:
    - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: pretty

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - .direnv

social_icons:
  - RSS

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"

